### ISSUE TITLE
Bad layout admin/dashboard.jsp

### ISSUE THREAD

**Issue by hoanghung256** [hoanghung256/event-management#31]
- @minhthangqhqn
![image](https://github.com/user-attachments/assets/9262adf9-7799-4486-8986-d795c48bf083)

**Comment by minhthangqhqn** [comment]
Ohh quên chưa add class cho th này hehe

Vào Th 4, 16 thg 10, 2024 lúc 00:22 Hoang Vu Hung ***@***.***>
đã viết:
