### ISSUE TITLE
search event còn lỗi

### ISSUE THREAD

**Issue by khimmap** [hoanghung256/event-management#33]
https://github.com/hoanghung256/event-management/blob/414a44ddf7036821f35f90de404845ab9e3c9c2f/src/main/webapp/club/dashboard.jsp#L7

**Comment by khimmap** [comment]
search + di chuột vào bị trắng ở total event @minhthang165 @ @

**Comment by hoanghung256** [comment]
@khimmap club dashboard không có search event

**Comment by khimmap** [comment]
ủa cái trang nào mà có cái filter evenr đầu trang ta

Huynh Viet Khiem


Vào Th 4, 16 thg 10, 2024 lúc 14:58 Hoang Vu Hung ***@***.***>
đã viết:

**Comment by khimmap** [comment]
xin lỗi trang này của student nhê
