### ISSUE TITLE
event details ở upcomming event chưa gắn link

### ISSUE THREAD

**Issue by khimmap** [hoanghung256/event-management#35]
https://github.com/hoanghung256/event-management/blob/414a44ddf7036821f35f90de404845ab9e3c9c2f/src/main/webapp/admin/dashboard.jsp#L349
@minhthang165 
thêm cả organizer event cũng chưa gắn link
3 cái cục ở trên di chuột bị trắng

**Comment by hoanghung256** [comment]
fix in PR #43
