### ISSUE TITLE
delete student k được

### ISSUE THREAD

**Issue by khimmap** [hoanghung256/event-management#37]
https://github.com/hoanghung256/event-management/blob/414a44ddf7036821f35f90de404845ab9e3c9c2f/src/main/webapp/admin/manage-student.jsp#L516
@huytbh308  @hoanghung256

**Comment by hoanghung256** [comment]
@huytbh308 fix này chưa cậu nhỉ

**Comment by hoanghung256** [comment]
- do chưa run db lastest version
