### ISSUE TITLE
(update) SEARCH EVENT LỖI

### ISSUE THREAD

**Issue by khimmap** [hoanghung256/event-management#39]
https://github.com/hoanghung256/event-management/blob/414a44ddf7036821f35f90de404845ab9e3c9c2f/src/main/webapp/homepage.jsp#L9
@motuen66  @hoanghung256

**Comment by hoanghung256** [comment]
@motuen66 
- Hình như thêm default value ;là 1 cái empty string cho default option là được, fix thử xem
- Line 38 homepage.jsp origin/master
`<option disabled selected value="">Select Category</option>`
- Line 50 homepage.jsp origin/master
`<option disabled selected value="">Select Organizer</option>`

**Comment by hoanghung256** [comment]
fix in PR #44
