### ISSUE TITLE
missing case sign up

### ISSUE THREAD

**Issue by huytbh308** [hoanghung256/event-management#40]
https://github.com/hoanghung256/event-management/blob/414a44ddf7036821f35f90de404845ab9e3c9c2f/src/main/java/com/fuem/controllers/SignUpController.java#L22

@khimmap 
- Vào sign up không nhập gì cả -> bấm nút signUp thì server error 
![image](https://github.com/user-attachments/assets/273d3944-fd04-4634-87e3-99dadb3c8c97)
![image](https://github.com/user-attachments/assets/a7e4c21d-9d62-4739-be0a-e910ac5173c6)

**Comment by khimmap** [comment]
kệ cậu hihi

Huynh Viet Khiem


Vào Th 4, 16 thg 10, 2024 lúc 21:32 Trịnh Bá Hoàng Huy <
***@***.***> đã viết:

**Comment by huytbh308** [comment]
validate lại gmail và mã sinh viên phải trùng nhau 
ví dụ: de180057 -> huytbhde180057@fpt.edu.vn

**Comment by khimmap** [comment]
lêu lêu

Vào Th 4, 16 thg 10, 2024 lúc 21:46 Trịnh Bá Hoàng Huy <
***@***.***> đã viết:

**Comment by huytbh308** [comment]
nhập kí tự đặc biệt vào fullname vẫn cho phép đăng ký tài khoản 
![image](https://github.com/user-attachments/assets/6f6cbdb3-6253-4764-8ca0-5a10327c46dd)

**Comment by khimmap** [comment]
dạ em đang check sign up ạ. Các bug sign up k cần make issue em sẽ check
toàn bộ ạ

Huynh Viet Khiem


Vào Th 4, 16 thg 10, 2024 lúc 21:57 Trịnh Bá Hoàng Huy <
***@***.***> đã viết:

**Comment by khimmap** [comment]
Got it, thanks!


Vào Th 6, 8 thg 11, 2024 lúc 20:29 Trịnh Bá Hoàng Huy <
***@***.***> đã viết:
