### ISSUE TITLE
thêm chọn gender khi sign up

### ISSUE THREAD

**Issue by khimmap** [hoanghung256/event-management#50]
https://github.com/hoanghung256/event-management/blob/e70c0e62e36dfa3680d048640b13c2467b7c04a7/src/main/java/com/fuem/controllers/SignUpController.java#L16

**Comment by hoanghung256** [comment]
@khimmap
- Làm luôn thêm get gender trong student-profile.jsp và student/profile.jsp. 2 jsp khác nhau đấy nhớ để ý.

**Comment by hoanghung256** [comment]
@khimmap đã xong issue này chưa nhỉ, nếu chưa thì mai hoàn thiện -> tạo PR

**Comment by khimmap** [comment]
xong ở trang sign up rầu

Huynh Viet Khiem


Vào CN, 20 thg 10, 2024 lúc 01:01 Hoang Vu Hung ***@***.***>
đã viết:

**Comment by hoanghung256** [comment]
resolve issue in PR #56
