### ISSUE TITLE
Change image url but image does not change at FE

### ISSUE THREAD

**Issue by hoanghung256** [hoanghung256/event-management#51]
https://github.com/hoanghung256/event-management/blob/62432feb29ea33076b55c8886da041c6034237c3/src/main/webapp/authentication/forget-password.jsp#L85

**Comment by hoanghung256** [comment]
@khimmap thử dùng <c:url> xem

```
 <div class="sign__input-thumb" data-background="<c:url value="assets/img/sign/forgetpassword1.jpg" />"> 
```

**Comment by khimmap** [comment]
forget password from minh thắng with love

Huynh Viet Khiem


Vào Th 3, 22 thg 10, 2024 lúc 18:30 Hoang Vu Hung ***@***.***>
đã viết:
