### ISSUE TITLE
Missing case Sign In with gmail account

### ISSUE THREAD

**Issue by hoanghung256** [hoanghung256/event-management#55]
@khimmap
- Reference to **FUNC-SignIn-04** [B02-RT02_BlockTesting_V1.0.xlsx](https://docs.google.com/spreadsheets/d/1KxT5gr-S8ZNiGYSrdGkVeryurjcEUBsM/edit?gid=1195864008#gid=1195864008)
- Description: Wrong redirect uri when user use a mail not exist in datasbase -> Must redirect back to Sign In page and display error message.
- Tester: @emtudeptrai

**Comment by khimmap** [comment]
là sao hok hẻo

Huynh Viet Khiem


Vào Th 7, 19 thg 10, 2024 lúc 23:51 Hoang Vu Hung ***@***.***>
đã viết:

**Comment by hoanghung256** [comment]
- Sign In với email k có trong database => error 500

**Comment by hoanghung256** [comment]
- Non-existent issue
- Baos laos
