### ISSUE TITLE
Bad UI/UX student profile

### ISSUE THREAD

**Issue by hoanghung256** [hoanghung256/event-management#60]
- Layout xiên xẹo, không thẳng hàng
- Chữ đang in đậm hết. Label in đậm còn content thì như bình thường
![image](https://github.com/user-attachments/assets/ac7b0370-305f-4518-a037-9a904fe617a6)

**Comment by hoanghung256** [comment]
![image](https://github.com/user-attachments/assets/b69871c6-9dde-4d65-8de9-01a55b0500fa)

**Comment by huytbh308** [comment]
damn

**Comment by hoanghung256** [comment]
- resolve issue in PR #69
