### ISSUE TITLE
avatardefault-error

### ISSUE THREAD

**Issue by huytbh308** [hoanghung256/event-management#71]
![image](https://github.com/user-attachments/assets/55881b62-e91a-4404-8293-1b7649d58c81)

**Comment by hoanghung256** [comment]
@huytbh308 
- Này tớ sẽ xử lý sau cậu.
- Tớ tính là khi có user signup hoặc được tọa mới bởi admin thì sẽ auto insert cái avatarPath default vào databse

**Comment by hoanghung256** [comment]
- resolved
